### ISSUE TITLE
Compiled Package

### ISSUE THREAD

**Issue by trichner** [mbrennan/passport-eveonline#1]
The npm package for passport-eveonline seems to only contain coffee-script. Would it be possible to provide a compiled js variant?

**Comment by mbrennan** [comment]
Hi Trichner, when you `npm install passport-eveonline`, only the Javascript is installed, not the source.    However, if you run the following commands:

```
git clone https://github.com/mbrennan/passport-eveonline.git
cd passport-eveonline
npm install
npm exec build
```

The `lib` directory will have all of the Javascript too.

Cheers,
Mike

**Comment by trichner** [comment]
Ah, this worked. Thank you.

But running `npm install passport-eveonline` doesnt, it ends up without the compiled coffeescript. Since this is also what happens if I include it in my dependencies this is kind of bad. Do you know a proper fix for this?

**Comment by mbrennan** [comment]
That's correct, the npm package itself contains no CoffeeScript source code, only the Javascript.  If you  want to install the source as part of your npm package, you can [use the git repository as an npm dependency](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

If you prefer to do that, you will have to manually run `npm exec build` as part of your build process or if you're using gulp, you can run `gulp build` against the `Gulpfile.coffee` included in the root of the package.

**Comment by trichner** [comment]
Ok, seems to be fixed now. I guess the npm build failed at some point as I cannot reproduce my own problem any longer xD.
Thanks for your help.
